name       : perl-net-dbus
version    : 1.2.0
release    : 9
source     :
    - http://search.cpan.org/CPAN/authors/id/D/DA/DANBERR/Net-DBus-1.2.0.tar.gz : e7a1ac9ef4a1235b3fdbd5888f86c347182306467bd79abc9b0756a64b441cbc
homepage   : https://metacpan.org/pod/Net::DBus
license    : GPL-2.0-or-later
component  : programming.perl
summary    : Net::DBus - Perl extension for the DBus message system
description: |
    Net::DBus provides a Perl API for the DBus message system. The DBus Perl interface is currently operating against the 0.32 development version of DBus, but should work with later versions too, providing the API changes have not been too drastic.
builddeps  :
    - perl
rundeps    :
    - perl-xml-twig
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
