name       : perl-net-dbus
version    : 1.1.0
release    : 4
source     :
    - http://search.cpan.org/CPAN/authors/id/D/DA/DANBERR/Net-DBus-1.1.0.tar.gz : 8391696db9e96c374b72984c0bad9c7d1c9f3b4efe68f9ddf429a77548e0e269
license    : GPL-2.0
component  : programming.perl
summary    : Perl extension for the DBus message system
description: |
    Perl extension for the DBus message system
builddeps  :
    - perl
rundeps    :
    - perl-xml-twig
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
